# This is your sidebar TOC. The sidebar code loops through sections here and provides the appropriate formatting.

entries:
- title: Sidebar
  levels: one
  folders:

  - title: Introduction
    output: web
    folderitems:

    - title: Introduction
      url: /doc-config-intro.html
      output: web

  - title: Concepts and design
    output: web
    folderitems:

    - title: Model
      url: /doc-config-design-model.html
      output: web

    - title: Module
      url: /doc-config-design-module.html
      output: web

    - title: ClassificationNode
      url: /doc-config-design-classification-node.html
      output: web

    - title: Artifact
      url: /doc-config-design-artifact.html
      output: web

    - title: Module-Artifact mapping
      url: /doc-config-design-module-artifact-mapping.html
      output: web

    - title: NodePath
      url: /doc-config-design-node-path.html
      output: web

    - title: Version
      url: /doc-config-design-version.html
      output: web

    - title: ArtifactVersion
      url: /doc-config-design-artifact-version.html
      output: web

    - title: ModuleVersion
      url: /doc-config-design-module-version.html
      output: web

    - title: Version-ArtifactVersion mapping
      url: /doc-config-design-version-artifact-version-mapping.html
      output: web

    - title: References and dependencies (to do)
      url: /doc-config-design-references-dependencies.html
      output: web

    - title: ReferenceGraph (to do)
      url: /doc-config-design-reference-graph.html
      output: web

    - title: ReferencePath (to do)
      url: /doc-config-design-reference-path.html
      output: web

    - title: ReferencePathMatcher
      url: /doc-config-design-reference-path-matcher.html
      output: web

    - title: Root ModuleVersion (to do)
      url: /doc-config-design-root-module-version.html
      output: web

    - title: ExecContext (to do)
      url: /doc-config-design-exec-context.html
      output: web

    - title: Jobs (to do)
      url: /doc-config-design-jobs.html
      output: web

    - title: Tools (to do)
      url: /doc-config-design-tools.html
      output: web

    - title: Properties
      url: /doc-config-design-properties.html
      output: web

    - title: Tool bootstrap process
      url: /doc-config-design-tool-bootstrap-process.html
      output: web

  - title: Model plugins
    output: web
    folderitems:

    - title: ArtifactInfoPlugin (to do)
      url: /doc-config-model-plugins-ArtifactInfoPlugin.html
      output: web

    - title: ArtifactVersionManagerPlugin (to do)
      url: /doc-config-model-plugins-ArtifactVersionManagerPlugin.html
      output: web

    - title: ArtifactVersionMapperPlugin (to do)
      url: /doc-config-model-plugins-ArtifactVersionMapperPlugin.html
      output: web

    - title: BuilderPlugin (to do)
      url: /doc-config-model-plugins-BuilderPlugin.html
      output: web

    - title: FindModuleByArtifactGroupIdPlugin (to do)
      url: /doc-config-model-plugins-FindModuleByArtifactGroupIdPlugin.html
      output: web

    - title: JenkinsJobInfoPlugin (to do) 
      url: /doc-config-model-plugins-JenkinsJobInfoPlugin.html
      output: web

    - title: ModuleVersionMatcherPlugin (to do)
      url: /doc-config-model-plugins-ModuleVersionMatcherPlugin.html
      output: web

    - title: NodeInitPlugin (to do)
      url: /doc-config-model-plugins-NodeInitPlugin.html
      output: web

    - title: ReferenceManagerPlugin (to do)
      url: /doc-config-model-plugins-ReferenceManagerPlugin.html
      output: web

    - title: RemoteBuilderPlugin (to do)
      url: /doc-config-model-plugins-RemoteBuilderPlugin.html
      output: web

    - title: ScmPlugin (to do)
      url: /doc-config-model-plugins-ScmPlugin.html
      output: web

    - title: SelectDynamicVersionPlugin (to do)
      url: /doc-config-model-plugins-SelectDynamicVersionPlugin.html
      output: web

    - title: SelectStaticVersionPlugin (to do)
      url: /doc-config-model-plugins-SelectStaticVersionPlugin.html
      output: web

    - title: UndefinedDescendantNodeManagerPlugin (to do)
      url: /doc-config-model-plugins-UndefinedDescendantNodeManagerPlugin.html
      output: web

    - title: VersionClassifierPlugin (to do)
      url: /doc-config-model-plugins-VersionClassifierPlugin.html
      output: web

  - title: ExecContext plugins
    output: web
    folderitems:

    - title: CredentialStorePlugin (to do)
      url: /doc-config-exec-context-plugins-CredentialStorePlugin.html
      output: web

    - title: EventPlugin (to do)
      url: /doc-config-exec-context-plugins-EventPlugin.html
      output: web

    - title: RuntimePropertiesPlugin (to do)
      url: /doc-config-exec-context-plugins-RuntimePropertiesPlugin.html
      output: web

    - title: UserInteractionCallbackPlugin (to do)
      url: /doc-config-exec-context-plugins-UserInteractionCallbackPlugin.html
      output: web

    - title: WorkspacePlugin (to do)
      url: /doc-config-exec-context-plugins-WorkspacePlugin.html
      output: web

  - title: Configuration
    output: web
    folderitems:

    - title: Model properties (to do)
      url: /doc-config-config-model-properties.html
      output: web

    - title: ExecContext properties (to do)
      url: /doc-config-config-exec-context-properties.html
      output: web

    - title: Tool properties (to do)
      url: /doc-config-config-tool-properties.html
      output: web

    - title: Initialization properties (to do)
      url: /doc-config-config-init-properties.html
      output: web

    - title: Java system properties (to do)
      url: /doc-config-config-sys-properties.html
      output: web

    - title: Runtime properties (to do)
      url: /doc-config-config-runtime-properties.html
      output: web

    - title: '"Do you want to continue?" contexts (to do)'
      url: /doc-config-config-do-you-want-to-continue-contexts.html
      output: web

    - title: Exceptional conditions (to do)
      url: /doc-config-config-exceptional-conditions.html
      output: web

  - title: Jobs
    output: web
    folderitems:

    - title: Build (to do)
      url: /doc-config-jobs-Build.html
      output: web

    - title: BuildReferenceGraph (to do)
      url: /doc-config-jobs-BuildReferenceGraph.html
      output: web

    - title: BuildRemote (to do)
      url: /doc-config-jobs-BuildRemote.html
      output: web

    - title: ChangeReferenceToModuleVersion (to do)
      url: /doc-config-jobs-ChangeReferenceToModuleVersion.html
      output: web

    - title: Checkout (to do)
      url: /doc-config-jobs-Checkout.html
      output: web

    - title: MergeMain (to do)
      url: /doc-config-jobs-MergeMain.html
      output: web

    - title: MergeReferenceGraph (to do)
      url: /doc-config-jobs-MergeReferenceGraph.html
      output: web

    - title: ReferenceGraphReport (to do)
      url: /doc-config-jobs-ReferenceGraphReport.html
      output: web

    - title: Release (to do)
      url: /doc-config-jobs-Release.html
      output: web

    - title: RootManager (to do)
      url: /doc-config-jobs-RootManager.html
      output: web

    - title: SetupJenkinsJob (to do)
      url: /doc-config-jobs-SetupJenkinsJobs.html
      output: web

    - title: SwitchToDynamicVersion (to do)
      url: /doc-config-jobs-SwitchToDynamicVersion.html
      output: web

  - title: Tools
    output: web
    folderitems:

    - title: DragomToolInvoker (to do)
      url: /doc-config-tools-DragomToolInvoker.html
      output: web

    - title: CredentialManagerTool (to do)
      url: /doc-config-tools-CredentialManagerTool.html
      output: web

    - title: ExecContextManagerTool (to do)
      url: /doc-config-tools-ExecContextManagerTool.html
      output: web

    - title: GenericRootModuleVersionJobInvokerTool (to do)
      url: /doc-config-tools-GenericRootModuleVersionJobInvokerTool.html
      output: web

    - title: ReferenceGraphReportTool (to do)
      url: /doc-config-tools-ReferenceGraphReportTool.html
      output: web

    - title: RootManagerTool (to do)
      url: /doc-config-tools-RootManagerTool.html
      output: web

    - title: SetupJenkinsJobsTool (to do)
      url: /doc-config-tools-SetupJenkinsJobsTool.html
      output: web

    - title: WorkspaceManagerTool (to do)
      url: /doc-config-tools-WorkspaceManagerTool.html
      output: web

  - title: Model plugin implementations
    output: web
    folderitems:

    - title: ConfigArtifactVersionMapperPluginImpl (to do)
      url: /doc-config-model-plugin-impls-ConfigArtifactVersionMapperPluginImpl.html
      output: web

    - title: ContinuousReleaseSelectStaticVersionPluginImpl  (to do)
      url: /doc-config-model-plugin-impls-ContinuousReleaseSelectStaticVersionPluginImpl.html
      output: web

    - title: GitScmPluginImpl (to do)
      url: /doc-config-model-plugin-impls-GitScmPluginImpl.html
      output: web

    - title: HotfixSelectDynamicVersionPluginImpl (to do)
      url: /doc-config-model-plugin-impls-HotfixSelectDynamicVersionPluginImpl.html
      output: web

    - title: JenkinsRemoteBuilderPluginImpl (to do)
      url: /doc-config-model-plugin-impls-JenkinsRemoteBuilderPluginImpl.html
      output: web

    - title: MatchAllModuleVersionMatcherPluginImpl (to do)
      url: /doc-config-model-plugin-impls-MatchAllModuleVersionMatcherPluginImpl.html
      output: web

    - title: MavenArtifactVersionManagerPluginImpl (to do)
      url: /doc-config-model-plugin-impls-MavenArtifactVersionManagerPluginImpl.html
      output: web

    - title: MavenBuilderPluginImpl (to do)
      url: /doc-config-model-plugin-impls-MavenBuilderPluginImpl.html
      output: web

    - title: MavenReferenceManagerPluginImpl (to do)
      url: /doc-config-model-plugin-impls-MavenReferenceManagerPluginImpl.html
      output: web

    - title: PhaseSelectDynamicVersionPluginImpl (to do)
      url: /doc-config-model-plugin-impls-PhaseSelectDynamicVersionPluginImpl.html
      output: web

    - title: PhaseSelectStaticVersionPluginImpl (to do)
      url: /doc-config-model-plugin-impls-PhaseSelectStaticVersionPluginImpl.html
      output: web

    - title: RuntimeSelectionPluginFactory (to do)
      url: /doc-config-model-plugin-impls-RuntimeSelectionPluginFactory.html
      output: web

    - title: SemanticSelectStaticVersionPluginImpl (to do)
      url: /doc-config-model-plugin-impls-SemanticSelectStaticVersionPluginImpl.html
      output: web

    - title: SimpleArtifactInfoPluginImpl (to do)
      url: /doc-config-model-plugin-impls-SimpleArtifactInfoPluginImpl.html
      output: web

    - title: SimpleArtifactVersionMapperPluginImpl (to do)
      url: /doc-config-model-plugin-impls-SimpleArtifactVersionMapperPluginImpl.html
      output: web

    - title: SimpleFindModuleByArtifactGroupIdPluginImpl (to do)
      url: /doc-config-model-plugin-impls-SimpleFindModuleByArtifactGroupIdPluginImpl.html
      output: web

    - title: SimpleVersionClassifierPluginImpl (to do)
      url: /doc-config-model-plugin-impls-SimpleVersionClassifierPluginImpl.html
      output: web

    - title: SimpleDynamicUndefinedDescendantNodeManagerModulePluginImpl (to do)
      url: /doc-config-model-plugin-impls-SimpleDynamicUndefinedDescendantNodeManagerModulePluginImpl.html
      output: web

    - title: UniformSelectDynamicVersionPluginImpl (to do)
      url: /doc-config-model-plugin-impls-UniformSelectDynamicVersionPluginImpl.html
      output: web

    - title: UniformSelectStaticVersionPluginImpl (to do)
      url: /doc-config-model-plugin-impls-UniformSelectStaticVersionPluginImpl.html
      output: web

  - title: ExecContext plugin implementations
    output: web
    folderitems:

    - title: DefaultCredentialStorePluginImpl (to do)
      url: /doc-config-exec-context-plugin-impls-DefaultCredentialStorePluginImpl.html
      output: web

    - title: DefaultEventPluginImpl (to do)
      url: /doc-config-exec-context-plugin-impls-DefaultEventPluginImpl.html
      output: web

    - title: DefaultRuntimePropertiesPluginImpl (to do)
      url: /doc-config-exec-context-plugin-impls-DefaultRuntimePropertiesPluginImpl.html
      output: web

    - title: DefaultUserInteractionCallbackPluginImpl (to do)
      url: /doc-config-exec-context-plugin-impls-DefaultUserInteractionCallbackPluginImpl.html
      output: web

    - title: DefaultWorkspacePluginFactory (to do)
      url: /doc-config-exec-context-plugin-impls-DefaultWorkspacePluginFactory.html
      output: web

    - title: MainModuleVersionWorkspacePluginFactory (to do)
      url: /doc-config-exec-context-plugin-impls-MainModuleVersionWorkspacePluginFactory.html
      output: web
